### PR TITLE
PatchOperation.AddIfAbsent

### PR DESCRIPTION
**Pull request by Inglix**
Something I found myself needing today. A small modification of PatchOperation.Set which will add the value if the node doesn't already exist, but will otherwise do nothing instead of replacing it.

### CODE REVIEW

**Comment by notfood** [comment]
Wouldn't it be better as an option to Set? The code seems exactly the same except for the comparison.

**Comment by Inglix** [comment]
Yes you're right. I've updated per your suggestion.

**Comment by notfood** [comment]
All good, my nitpick is the keyword `replaceExisting=true`. How about `ignoreExisting=false`? or `skipExisting=false`? Or better yet, `skip=Conflict`, `skip=Adding`, `skip=None`.

`skip=Adding`  would be useful for those situations where you target all the childrens of a parent template and you don't want to set a default in case someone else overrides the parent.

What do you think?

**Comment by Inglix** [comment]
That sounds pretty good. I'll try it out later this morning and update the pull request once I've tested it.

**Comment by Inglix** [comment]
What would you think of using `Replacing` instead of `Conflict`? It feels like it fits better alongside `Adding`.

**Comment by notfood** [comment]
Sounds good

**Pull request merged**
